description: Returns answers related to query on Usage of Test Data in Tests and Test Automates, S/4HANA Cloud, On-Premise, Product versions, Business configuration, Mocking, Test pyramid, Test data, Unit tests, Integration tests, Test Data Engineering (TDE), Test Data Framework (TDF), Quality at Transport Level (QATL), Quality at Pretest System (QAPS), API test tools, Performance test data
slots:
- name: userinput
  description: complete input received from user in assistant

target:
  type: function
  name: WIKI/fetch_wiki_test_environment

response_context:
- description: Response from wiki
  value: response
