description: Returns answers related to query on Delivery Code Line, ATC System, ABAP Unit Tests,Regression Tests, Integration Tests, Performance Measurements, Infinity Landscape,Main Release Delivery, CFD Delivery, Maintenance Code Line, Test Automates, Dry Run, Integration Qualification (IQ),Automated Integration Qualification (AIQ),Manual Integration Qualification (MIQ), CILTS Tool, Test Coverage Dependencies, Qmate, Feature Based Engineering (FBE), Decentralized Docker Environment (DDCI)
slots:
  - name: userinput
    description: complete input received from user in assistant
  
target:
  type: function
  name: WIKI/fetch_wiki_test_environment

response_context:
  - description: Response from wiki
    value: response
