description: Returns answers related to query on Pre-Integration Qualification Test Environment (Public Cloud), Infinity Test Environment, Delivery Test Environment, Functional Correctness, Solution Builder Systems, Ledger 2L – IFRS, Content Cascade, Golden Template CE2308, PSM GTC, Early SSCUI Tests, Early manual tests, JVA Automated Tests, Development Extensibility, HANA Cloud Performance, 1S4HC D2P Tests, Banking Automated Tests, Full BP Scope, CBC master branch, CLDFND tests, Globalization tests
slots:
- name: userinput
  description: complete input received from user in assistant

target:
  type: function
  name: WIKI/fetch_wiki_test_environment

response_context:
- description: Response from wiki
  value: response
