description: Returns answers related to query on SComp (Public Cloud), 2SL system landscape, 3SL test landscape, CFD test landscape, CBC test landscape, Test Data Engineering (TDE), SComp, Master data, Tag in TDE, Handover process, SComp Repo, Golden Test Client, Verification of test data, SComp Preparation cycle, OData API, S4HCE 2402, Procurement of Direct products, Project-based Service, System refresh, Content provisioning
slots:
- name: userinput
  description: complete input received from user in assistant

target:
  type: function
  name: WIKI/fetch_wiki_test_environment

response_context:
- description: Response from wiki
  value: response
